-- 5PennyAi blog schema
-- Run this in the Supabase SQL editor (https://supabase.com/dashboard → your project → SQL Editor).

create table posts (
  id uuid default gen_random_uuid() primary key,
  slug text unique not null,
  status text default 'draft' check (status in ('draft', 'published', 'archived')),

  -- FR content
  title_fr text not null,
  excerpt_fr text,
  content_fr text not null,

  -- EN content
  title_en text,
  excerpt_en text,
  content_en text,

  -- Media
  cover_image text, -- Public URL from the Storage bucket

  -- Metadata
  tags text[] default '{}',
  author text default 'Christian Couillard',
  reading_time_minutes int,

  -- SEO
  meta_title_fr text,
  meta_description_fr text,
  meta_title_en text,
  meta_description_en text,

  -- Dates
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes for frequent queries
create index idx_posts_status on posts(status);
create index idx_posts_published_at on posts(published_at desc);
create index idx_posts_slug on posts(slug);

-- Auto-update updated_at on every row change
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger posts_updated_at
  before update on posts
  for each row
  execute function update_updated_at();

-- Row level security
alter table posts enable row level security;

-- Public can only read published posts
create policy "Public can read published posts"
  on posts for select
  using (status = 'published');

-- Service role (server-side, e.g. n8n workflows) has full access
create policy "Service role full access"
  on posts for all
  using (auth.role() = 'service_role');

-- Authenticated users can manage posts (admin UI in the site uses supabase.auth)
-- The frontend still gates the UI by email (see src/components/admin/AdminGuard.jsx),
-- so this policy is scoped to any authenticated session.
create policy "Authenticated can manage posts"
  on posts for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- =============================================================================
-- STORAGE BUCKET — manual setup in the Supabase Dashboard
-- =============================================================================
-- 1. Storage → New bucket → name: "blog-images", public: true.
-- 2. Policies on the bucket:
--    a) Public read:
--       create policy "Public read blog-images"
--         on storage.objects for select
--         using (bucket_id = 'blog-images');
--    b) Authenticated upload (used by the admin UI):
--       create policy "Authenticated upload blog-images"
--         on storage.objects for insert
--         with check (bucket_id = 'blog-images' and auth.role() = 'authenticated');
-- 3. The n8n workflow uses the service_role key and bypasses RLS.
-- 4. Public URL format:
--    https://[PROJECT_ID].supabase.co/storage/v1/object/public/blog-images/[filename]
-- 5. Infographics generated by /api/generate-infographic are stored at:
--    blog-images/infographics/{slug}-{scope}-{lang}-{timestamp}.png

-- =============================================================================
-- MIGRATION — Bilingual cover / header image columns on posts
-- =============================================================================
-- Adds six columns used by the Nano Banana Header workflow
-- (/api/generate-header + HeaderImageGenerator). The legacy `cover_image`
-- column stays as a fallback for articles that were created before the bilingual
-- workflow.
--
-- IDEMPOTENT: safe to re-run. Copy into the Supabase SQL Editor and execute.
-- =============================================================================

alter table posts add column if not exists cover_image_fr text;
alter table posts add column if not exists cover_image_en text;
alter table posts add column if not exists cover_image_alt_fr text;
alter table posts add column if not exists cover_image_alt_en text;
alter table posts add column if not exists cover_image_category text;
alter table posts add column if not exists cover_image_mode text;

-- Storage convention: blog-images/headers/{slug}-{lang}-{timestamp}.png

-- =============================================================================
-- MIGRATION — article_infographics
-- =============================================================================
-- Tracks Nano Banana infographies generated per post.
-- Used by /api/generate-infographic + src/components/admin/InfographicGenerator.jsx.
--
-- This block is IDEMPOTENT: safe to re-run on an existing database. Copy this
-- section into the Supabase SQL Editor and execute. It does not touch the
-- existing `posts`, `topics`, or `topic_searches` tables.
-- =============================================================================

create table if not exists article_infographics (
  id               uuid default gen_random_uuid() primary key,
  post_id          uuid references posts(id) on delete cascade,

  -- Scope of the infographic within the article
  scope            text not null check (scope in ('global', 'section')),
  section_index    int,            -- index in extractH2Sections() result, null if global
  section_title    text,           -- snapshot of the section title (for debug / display)

  -- Prompt metadata (from Claude + skill)
  type             text not null,  -- e.g. 'catalogue_7a', 'process_2', 'comparison_3'
  format           text not null,  -- '16:9' | '4:5' | '1:1' | '3:4'
  takeaway_variant text,            -- 'A'..'E' (rotation across an article's series)

  -- Prompts and alt texts (bilingual)
  prompt_fr        text not null,
  prompt_en        text not null,
  alt_fr           text not null,
  alt_en           text not null,

  -- Final image URLs (Supabase Storage, public bucket blog-images)
  image_url_fr     text,
  image_url_en     text,

  -- Generation tracking
  model_version    text default 'gemini-3-pro-image-preview',
  temperature      numeric default 0.4,
  status           text default 'draft' check (status in ('draft', 'validated', 'published')),

  created_at       timestamptz default now()
);

create index if not exists idx_article_infographics_post
  on article_infographics(post_id);
create index if not exists idx_article_infographics_post_scope
  on article_infographics(post_id, scope);

alter table article_infographics enable row level security;

-- Drop existing policies first so this block stays idempotent
drop policy if exists "Service role full access on article_infographics" on article_infographics;
drop policy if exists "Authenticated can manage article_infographics"    on article_infographics;
drop policy if exists "Public can read validated article_infographics"   on article_infographics;

-- Service role (server-side) has full access
create policy "Service role full access on article_infographics"
  on article_infographics for all
  using (auth.role() = 'service_role');

-- Authenticated admin users can manage all rows (frontend gates by email)
create policy "Authenticated can manage article_infographics"
  on article_infographics for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Public can read only validated/published infographics
create policy "Public can read validated article_infographics"
  on article_infographics for select
  using (status in ('validated', 'published'));
